### ISSUE TITLE
Синонимы типов

### ISSUE THREAD

**Issue by roman-bodavskiy** [LyuPo7/bot#11]
Синонимы типов 
```
type UserId = Integer
type ChatId = Integer
```
не добавляют безопасности коду, то есть мы можем вместо `UserId` всегда подставить `ChatId`. И вместе с тем, это уменьшает понимание, так как проверяющий не знает, что `ChatId` это не какой-то специфический тип, а просто `Int`.
Рекомендуется (на твое усмотрение) сделать `newtype` обертки, например 
`newtype UpdateId = UpdateId Int deriving newtype (Show, FromJSON, ToJSON, Convert, Num, Read, Ord, Eq)`
механизм дерайва позволяет с ними работать, как с обычными типами, взамен мы получаем типобезопасность и никакого оверхеда в реалтайме

**Comment by LyuPo7** [comment]
Поменяла все type на newtype
