### ISSUE TITLE
Класс Worker

### ISSUE THREAD

**Issue by roman-bodavskiy** [LyuPo7/bot#13]
Можешь объяснить предназначение класса Worker
`class (MonadThrow m, Monad m) => Worker m api where`
который имеет только один инстанс
`instance (MonadThrow m, Monad m) => Worker m BotApi.Api where`

**Comment by LyuPo7** [comment]
Класс настраивает методы бота для работы с обновлениями и сообщениями.
В инстансе в зависимости от выбранного Api выбирается реализация для методов (для Telegram или Vk).
Изначально Я хотела сделать для каждого Api свой инстанс, но потом, чтобы не вводить дополнительный маркер сделала один инстанс для двух Api.

> Можешь объяснить предназначение класса Worker `class (MonadThrow m, Monad m) => Worker m api where` который имеет только один инстанс `instance (MonadThrow m, Monad m) => Worker m BotApi.Api where`

**Comment by KateBushueva** [comment]
может быть, тут еще вопрос в наименовании? можно именовать вместо `Worker` во что-то типа `BotApi`

**Comment by LyuPo7** [comment]
Насчет именования согласна: Worker - неудачно.
Воспользовалась предложением Kate - поменяла на `BotApi`

> может быть, тут еще вопрос в наименовании? можно именовать вместо `Worker` во что-то типа `BotApi`

**Comment by roman-bodavskiy** [comment]
Просто я говорю о том имеет ли смысл делать класс, если у него только один инстанс
Если сделать два инстанса 
```
data VK = VK
data Telegram = Telegram

instance (MonadThrow m, Monad m) => Worker m VK where
instance (MonadThrow m, Monad m) => Worker m Telegram where
```
тогда это будет иметь смысл. Может еще для тестов инстанс.
Либо просто удалить этот класс и оставить простые функции. Можно написать их в какой-то отдельный модуль, если хочешь выделить

**Comment by LyuPo7** [comment]
Удалила класс.
Методы, ранее принадлежащие классу, вынесла в отдельный модуль

> Просто я говорю о том имеет ли смысл делать класс, если у него только один инстанс Если сделать два инстанса
> 
> ```
> data VK = VK
> data Telegram = Telegram
> 
> instance (MonadThrow m, Monad m) => Worker m VK where
> instance (MonadThrow m, Monad m) => Worker m Telegram where
> ```
> 
> тогда это будет иметь смысл. Может еще для тестов инстанс. Либо просто удалить этот класс и оставить простые функции. Можно написать их в какой-то отдельный модуль, если хочешь выделить
