### ISSUE TITLE
Импорты

### ISSUE THREAD

**Issue by roman-bodavskiy** [LyuPo7/bot#3]
Привет) Не везде используются списки импорта. Нужно использовать либо списки импорта, либо квалифицированные. Например, в тестах лучше написать import qualified. 
https://github.com/LyuPo7/bot/blob/64a0283be10ef5af413fd006518df72cd4fccf6d/test/TestBot/Tele/Run.hs#L7

Если ты используешь hls в vscode, то он сам предлагает сделать списки импорта где нужно

**Comment by LyuPo7** [comment]
Исправлено.

> Привет) Не везде используются списки импорта. Нужно использовать либо списки импорта, либо квалифицированные. Например, в тестах лучше написать import qualified.
