### ISSUE TITLE
Форматирование

### ISSUE THREAD

**Issue by roman-bodavskiy** [LyuPo7/bot#5]
Не пойму, какой форматтер у тебя используется. В src есть `fourmolu.yaml`, но используется не он. Количество пробелов в некоторых файлах равно 4.
Нужно использовать `ormolu` и количество пробелов 2

**Comment by roman-bodavskiy** [comment]
Пока не переделывай ничего, я уточню требования...

**Comment by LyuPo7** [comment]
Все-таки сделала везде по 2 пробела, лучше когда везде одинаковое форматирование.
> Пока не переделывай ничего, я уточню требования...

**Comment by KateBushueva** [comment]
Если ты сидишь на Линуксе, есть такая утилита Makefile, куда можно занести скрипты для форматирования сразу всего проекта одной командой. Также туда можно занести команды для прохода по проекту хлинтом. Это довольно простая и полезная вещь
