### ISSUE TITLE
Проверка орфографии

### ISSUE THREAD

**Issue by roman-bodavskiy** [LyuPo7/bot#6]
В именах функций и переменных допускаются только английские слова или общепринятые сокращения в camelCase. Например `hconfig` лучше исправить на `hConfig`. Также есть некоторые ошибки и опечатки в коде - verbocity, Unsuccessfull и т. д.

Если у тебя vscode, то там есть удобное расширение code spell checker для проверки орфографии.

**Comment by LyuPo7** [comment]
исправлено.

> В именах функций и переменных допускаются только английские слова или общепринятые сокращения в camelCase. Например `hconfig` лучше исправить на `hConfig`. Также есть некоторые ошибки и опечатки в коде - verbocity, Unsuccessfull и т. д.
> 
> Если у тебя vscode, то там есть удобное расширение code spell checker для проверки орфографии.
