### ISSUE TITLE
организация типов

### ISSUE THREAD

**Issue by KateBushueva** [LyuPo7/bot#8]
модуль `Bot.Vk.Parser.Data` : 
- дублирую коммент `с Attachment лучше использовать тип сумму, а не произведение: аттачмент может быть только одним из вышеперечисленных типов (а не может содержать сразу несколько ), это логически определение типа суммы (а не произведения)` 
- список имеет поддержку нулевого значения - пустой список, нет необходимости оборачивать список в монаду `Maybe` 

![Снимок экрана от 2021-11-08 16-25-08](https://user-images.githubusercontent.com/80405655/140750130-3b273c82-25fe-4865-b548-3f7821d9fa64.png)

**Comment by LyuPo7** [comment]
Поменяла Attachment тип на сумму.

>     * дублирую коммент `с Attachment лучше использовать тип сумму, а не произведение: аттачмент может быть только одним из вышеперечисленных типов (а не может содержать сразу несколько ), это логически определение типа суммы (а не произведения)`

**Comment by LyuPo7** [comment]
1. attachment :: Maybe [Attachment] - если парсится json в котором нет ключа attachment, будет Nothing
2. attachment :: [Attachment] - если парсится json в котором нет ключа attachment, будет ошибка.
Поэтому Я использую 1ый вариант в случаях, когда в json поле присутствует всегда.
Во всех остальных случаях использую вариант 2;
 
>     * список имеет поддержку нулевого значения - пустой список, нет необходимости оборачивать список в монаду `Maybe`

**Comment by LyuPo7** [comment]
Эти правки внесены вместе с коммит #7

**Comment by KateBushueva** [comment]
вроде в вк хотели еще убрать мэйби перед списком (тем более теперь инстанс `fromJSON` написан руками)

**Comment by LyuPo7** [comment]
Хотели, но это когда думали, что Vk присылает поле attachments всегда, - выяснилось что это не так.
Инстанс `fromJSON` написан руками для Attachment, а поле attachments в Message же (и Инстанс `fromJSON` для Message по-прежнему Generic)

> вроде в вк хотели еще убрать мэйби перед списком (тем более теперь инстанс `fromJSON` написан руками)

**Comment by KateBushueva** [comment]
> Хотели, но это когда думали, что Vk присылает поле attachments всегда, - выяснилось что это не так.
> Инстанс `fromJSON` написан руками для Attachment, а поле attachments в Message же (и Инстанс `fromJSON` для Message по-прежнему Generic)

ok

**Comment by KateBushueva** [comment]
в некоторых местах в коде встречаются АДТ-суммы с рекорд синтаксисом - такого лучше избегать, по сути 
`teleMessage` имеет сигнатуру `teleMessage :: Message -> TeleMessage.Message` , однако сама функция определена только для одного из заданных конструкторов - `TeleMessage` . В случае АДТ-суммы лучше избавиться от рекорд синтаксиса: 
```
data Message = TeleMessage TeleMessage.Message
  | VkMessage VkMessage.Message
   deriving (Show, Eq)
```


![Снимок экрана от 2021-11-17 14-35-47](https://user-images.githubusercontent.com/80405655/142193762-4604e2a8-661f-4b01-9875-e2ffccc5660c.png)

**Comment by LyuPo7** [comment]
Устранила!

> в некоторых местах в коде встречаются АДТ-суммы с рекорд синтаксисом - такого лучше избегать, по сути `teleMessage` имеет сигнатуру `teleMessage :: Message -> TeleMessage.Message` , однако сама функция определена только для одного из заданных конструкторов - `TeleMessage` . В случае АДТ-суммы лучше избавиться от рекорд синтаксиса:
