### ISSUE TITLE
Архитектура

### ISSUE THREAD

**Issue by KateBushueva** [LyuPo7/bot#9]
на данный момент весь бот по архитектуре лежит на одном уровне: для каждого мессенджера пишется и запускается свой бот. Это довольно непрактичный подход: 
- во-первых, при появлении нового мессенджера придется целиком почти писать для него программу
- во-вторых, появляется большое количество дублирующего кода
- в-третьих, при попытке внести изменения в бизнес-логику придется менять каждый случай отдельно
- в-четвертых, покрывать тестами придется каждого бота отдельно
Более грамотно построенная архитектура подразумевает вынесение бизнес-логики на абстрактный уровень, а задачей имплементации для мессенджера является подстановка конкретных имплементаций и значений в эту логику.

**Comment by KateBushueva** [comment]
К примеру, после успешного чтения конфига и установки настроек работа бота в общих чертах сводится к следующему: 
  1 получение сообщений с сервера
  2 обработка сообщений
  3 отправка сообщений на сервер
В данном случае шаг 2 можно вынести отдельно, он никак не зависит от вида мессенджера, эта часть программы должна быть общей для всех мессенджеров

**Comment by KateBushueva** [comment]
шаги 1 и 3 зависят от вида мессенджера в части "как это происходит", однако не зависят от вида мессенджера в части "что происходит", плюс здесь предусматривается коммуникация с внешним ресурсом - это почти хрестоматийсный пример применения хэндл паттерна

**Comment by KateBushueva** [comment]
Я бы рекомендовала все-таки вынести общую бизнес-логику отдельно

**Comment by KateBushueva** [comment]
по использованию Хэндлов - в хэндл кладутся функции или другие хэндлы, которые обычно используются для коммуникации с внешними ресурсами, то есть это способ абстрагироваться от ИО. Таким образом не корректно класть в хэндлы чистые функции и структуры данных, так как чистые функции и структуры мы можем без проблем брать из того места, где они определены.

**Comment by KateBushueva** [comment]
В данном примере для логгера и ДБ создание хэндлов оправдано, а для парсера сомневаюсь (так как парсинг вряд ли коммуницирует с внешним миром, для парсинга имеет смысл просто оставить чистые функции). `hRec` содержит внутри тоже логгер хэндл и дб хэндл..

**Comment by KateBushueva** [comment]
`cRun` по сути - это набор настроек, которые передаются в бот. Если бы мы работали в ReaderT или StateT монаде, набор настроек можно было бы передавать в виде окружения или стейта.

**Comment by KateBushueva** [comment]
функции типа getChatId или getMessageText - по сути своей чистые функции, нет необходимости класть их в хэндл

**Comment by LyuPo7** [comment]
Убрала из хэндлов чистые функции.
Убрала лишние хэндлы.
Добавила тайпклассы.

**Comment by KateBushueva** [comment]
Остался вопрос по бд-хэнлам: 
как я понимаю, есть 2 хэндла в модулях `DBQ` и `DB`, при этом в `DB` есть только одно полезное поле - `conn :: Connection` , остальные поля дублируются в обоих хэндлах. Может имеет смысл объединить эти хэндлы?
